markdown: kramdown
url:
staging_url:
baseurl:
exclude:
  - '/vendor'
  - 'README.md'
  - '.gitignore'
  - 'package.json'
  - 'node_modules'
  - 'Gemfile.lock'
  - 'Gemfile'
  - '_assets'
  - '_tests'
permalink: pretty
gems:
  - jekyll-sitemap
keep_files: ['assets']
ga_code: UA-91091144-1
title: SDWM
description: SDWM
twitter:
instagram_url:  https://www.instagram.com/sickdogwolfman/
collections:
  projects:
    output: true
    path: /projects/:path/
